config/routes.rb
Rails.application.routes.draw do

  root "events#index"
  devise_for :users
  resources :events do 
  	  resources :charges
      resources :attendances
      resources :avatars
  end 
  
  resources :teams
  resources :contacts
  #resources :users do
   # resources :avatars
  #end
  resources :user, :has_one => [:avatar]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	after_create :welcome_send
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  
	has_many :attendances
	has_many :events, through: :attendances
  has_many :organisations, foreign_key: 'admin_id', class_name: "Event"

  has_one_attached :avatar
  def welcome_send
  	UserMailer.welcome_email(self).deliver_now	
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #before_action :check_if_admin
    before_action :authenticate_user, only: [:show, :edit, :update, :destroy]
    before_action :is_owner, only: [:show, :edit, :update, :destroy]
    before_action :set_user, only: [:show, :edit, :update]


  def index
    @users = User.all
  end



  def show
    @user = User.find(params[:id])
    @admin_events = Event.where(admin_id: @user.id)
    (@admin_events.size > 0)? (@admin = true) : (@admin = false)
    @guest_events = Event.joins(:attendances).where('attendances.user_id = ?', @user.id)
    (@guest_events.size > 0)? (@guest = true) : (@guest = false)
    @avatar = @user.avatar
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(first_name: params[:first_name], 
                    last_name: params[:last_name],
                    description: params[:description],
                    email: params[:mail])
    @user.avatar.attach(params[:avatar])
    if params[:password] != params[:confirmpassword]
      flash.now[:danger] = "Passwords must match !"
      render :action => 'new' 
    end
    if @user.save # essaie de sauvegarder en base @gossip
        flash[:success] = "You successfuly created your account"
        redirect_to :controller => 'users', :action => 'index'
    else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      flash.now[:danger] = "Error with the account creation"
      render :action => 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
    
   def authenticate_user
      unless current_user 
        flash[:danger] = "This section requires to be logged-in. Please log in."
        redirect_to new_user_session_url
      end
    end

    def is_owner
      if current_user.id.to_i != params[:id].to_i
        flash[:danger] = "You can't acces this page"
        redirect_to "/"
      end
    end

    #def is_admin
     # if current_user.is_admin == false
     #   flash[:danger] = "You can't acces this page"
     #   redirect_to "/" 
    #  end  

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<!-- Header -->
<header class="bg-primary text-center py-5 mb-4">
  <div class="container">
    <h1 class="font-weight-light text-white">Meet <%= @user.first_name %> <%= @user.last_name %> !</h1>
  </div>
</header>

<!-- Page Content -->
<div class="container">
  <div class="row">
    <!-- Team Member 1 -->
    <div class="col-xl-3 col-md-12 mb-8">
      <div class="card border-0 shadow">
        <img src="https://source.unsplash.com/TMgQMXoglsM/500x350" class="card-img-top" alt="...">
        <div class="card-body text-center">
          <h2 class="card-title mb-0"> <%= @user.first_name %> <%= @user.last_name %> </h2> <br/>
      </div>
    </div>
</div>
</div>

<!-- PROFIL INFOS -->



<!-- Profile info -->

<div class ='align-middle'>
  <div class="card mt-5 ml-5 mr-5 p-4">
    <div class="card-body">

      <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar, alt: 'avatar' %>
<%else%>
  <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
      <% end  %>
      <h5 class="card-title"><%= @user.first_name %> <%= @user.last_name %></h5>
      <p class="card-title"><strong>Bio : </strong><%= @user.description %></p>
      <p class="card-title"><strong>Mail : </strong> <%= @user.email %></p>
      <p class="card-title"><strong>Profile created on : </strong><%= @user.created_at.strftime("%d/%m/%Y") %></p>
      <p class="card-title"> <strong>Last update on : </strong><%= @user.updated_at.strftime("%d/%m/%Y") %></p></br></br>
      <% if current_user.id == @user.id %>
        <%= link_to 'Edit Basic Info', edit_user_path(@user) %>  |
        <%= link_to "Edit your password", edit_user_registration_path(@user) %> |   
        <%= link_to 'Destroy', users_path(@event), method: :delete, data: { confirm: 'Are you sure?' }  %>
      <% end %>

</div>
</div>
</div>

<h3>Avatar actuel</h3>
<%if @avatar.attached?%>
  <%= image_tag @user.avatar, alt: 'avatar' %>
<%else%>
  <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
<%end%>


<%= form_for [@user, @avatar], :url => user_avatar_url(@user) do |f| %>
  <%= f.file_field_tag :avatar, placeholder: "Name" %>
  <%= f.submit_tag "uploader l'avatar" %>
<% end %>
</div>
</div>


<!-- /.container -->

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>