config/routes.rb
Rails.application.routes.draw do

  root "events#index"
  devise_for :users
  resources :events do 
  	  resources :charges
      resources :attendances
      resources :avatars
  end 
  
  resources :teams
  resources :contacts
  #resources :users do
   # resources :avatars
  #end
  resources :user, :has_one => [:avatar]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord

	has_many :attendances
	has_many :users , through: :attendances
	belongs_to :admin, class_name: "User"

	validates :start_date, presence: true 

	validates :duration, presence: true, :numericality => { :greater_than_or_equal_to => 0 }


	validates :title, presence: true, length: {minimum: 5, maximum: 140}

	validates :description, presence: true, length: {minimum: 20, maximum: 1000}

	validates :price, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 1000}

	validates :location, presence: true

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  before_action :authenticate_user!, only: [:new, :create, :show]
  before_action :is_owner, only: [:edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @user = current_user
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.admin_id = current_user.id
    respond_to do |format|
      if @event.save
        if params[:avatar]
        @event.avatar.attach(params[:avatar])
      else
        downloaded_image = open(Faker::LoremPixel.image(secure: false))
        @event.avatar.attach(io: downloaded_image  , filename: "faker.jpg")
      end
        flash[:success]= "Ton évenement a bien été créé !"
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event = Event.find(params[:id])
    respond_to do |format|
      if @event.update(event_params)
        @event.avatar.attach(params[:avatar])

        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


    private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = Event.find(params[:id]).admin_id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:start_date, :duration, :title, :price, :description, :location)
    end
    
    #NOMBRE DE USER INSCRIT À L'EVENT
      def count
        Event.find(params[:id]).users.all.count
      end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
    
   def authenticate_user
      unless current_user 
        flash[:danger] = "This section requires to be logged-in. Please log in."
        redirect_to new_user_session_url
      end
    end

    def is_owner
      if current_user.id.to_i != Event.find(params[:id]).admin_id
        flash[:danger] = "You can't acces this page"
        redirect_to "/"
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper

  def is_owner(event)
      current_user.id == event.admin_id
   end
end

app/views/events/_carousel.html.erb
	<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>THP - Week 7 - Project 2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!--  Font Awesome  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" crossorigin="anonymous">


      <!-- Latest compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


  </head>

  <body>


  <!-- Caroussel of Top 3 selling events -->
    <div class="carouselContainer mt-3 mb-3">
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
          <li data-target="#carousel-example-generic" data-slide-to="3"></li>
        </ol>
        <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="img-carousel" src="../app/assets/images/1.jpg" alt="Carousel">
            </div>

          <div class="carousel-item">
            <img src="../app/assets/images/2.png">
          </div>

          <div class="carousel-item">
            <img src="../app/assets/images/3.jpg">
          </div>

          <div class="carousel-item">
            <img src="../app/assets/images/4.jpg">
          </div>
        <!-- Controls -->
        <a class="carousel-control-prev" href="#carousel-example-generic" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carousel-example-generic" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
          </a>
      </div>
    </div>
  </div>
</body>
</html>

app/views/events/_index.html.erb
<section class="jumbotron">
  <h1>WELCOME</h1>
  <p>BEST WEBSITE TO FOLLOW YOUR FAVORITE EVENTS !</p>
  <%=link_to "CREATE YOUR EVENT", new_event_path, class: "button" %>
</section>

  <div class="container">
    <div class="row">
      <p> <% @events.each do |event|  %> </p>
        <div class="col-xs-12 col-md-4">
           <div class="container-card">
             <div class="card">
                 <div class="card__image-container">
                    <img class="card__image card-img" src="https://images.unsplash.com/photo-1519999482648-25049ddd37b1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2126&q=80" alt="">
                      </div>
                       <div class="card__content"><br/>
                       <h4 class="card-title font-weight-bold mb-2">Event <%= link_to event.title , event_path(:id => event.id) %> <br/>
                       Organisé par <%= link_to User.find(event.admin_id).first_name , user_path(:id =>  User.find(event.admin_id).id ) %></h4> 
                       <p class="card-text"><i class="far fa-clock pr-2"></i>Crée le <%=event.created_at%></p>

                     <p><%=event.description%></p>
                      <a class="btn btn-flat red-text p-1 my-1 mr-0 mml-1 collapsed" data-toggle="collapse" href="#collapseContent" aria-expanded="false" aria-controls="collapseContent"></a>
                      <i class="fas fa-share-alt text-muted float-right p-1 my-1" data-toggle="tooltip" data-placement="top" title="Share this post"></i>
                      <i class="fas fa-heart text-muted float-right p-1 my-1 mr-3" data-toggle="tooltip" data-placement="top" title="I like it"></i>
                    </div>
                  </div>
                </div>
              </div>
              <% end %> 
            </div>
          </div>

app/views/events/_show.html.erb
<div class="container">
	<div class="border_style">
      <div class="card-img-body">
      <img class="card-img" src="https://images.unsplash.com/photo-1535074153497-b08c5aa9c236?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=d2aaf944a59f16fe1fe72f5057b3a7dd&auto=format&fit=crop&w=500&q=80" alt="Card image cap">
      </div>
      <div class="card-body">
        <h4 class="card-title"><%= @event.title %></h4>
        <p class="card-text"> <%= @event.description %> <br/> Crée par <%= link_to User.find(@event.admin_id).first_name , user_path(:id =>  User.find(@event.admin_id).id) %> , price <%= @event.price %> </p>
         <% if is_owner(@event) %>
        <p class="btn btn-lg btn-primary btn-block"> <%= link_to "Mon espace événement" , event_attendances_path(@event) %> </p>
        <% else %>
         <p class="btn btn-lg btn-primary btn-block"> <%= link_to "Inscris toi !" , new_event_charge_path(@event) %> </p>
        <% end %>
      <i class="fas fa-share-alt text-muted float-right p-1 my-1" data-toggle="tooltip" data-placement="top" title="Share this post"></i>
      <i class="fas fa-heart text-muted float-right p-1 my-1 mr-3" data-toggle="tooltip" data-placement="top" title="I like it"></i>
        </div>
</div>
</div>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>

    <h1 class="h3 mb-3 font-weight-normal text-center">Modifie ton event !</h1>
  <!-- FORMULAIRE DE CRÉATION D'UN EVENT -->
  <%= form_with model: @event, local: true,  html: { class: "form-signin mt-3" } do |f| %>


    <p> Date de début :</br> <%= f.datetime_select :start_date, class: "form-control"%> </p>

    <p> Durée (en minutes) :</br> <%= f.number_field :duration, step: 5, min: 0, class: "form-control"%> </p>


    <p> Description :</br> <%= f.text_field :description, class: "form-control"%> </p>
    <p> Titre :</br> <%= f.text_field :title, class: "form-control"%> </p>


    <p> Prix  :</br> <%= f.number_field :price, min: 1, class: "form-control"%> </p>


    <p> Lieu de l'Event :</br> <%= f.text_field :location, class: "form-control"%></p>
    <div class="actions mt-5">
      <%= f.submit "Submit", class: "btn btn-lg btn-primary btn-block" %>
    </div>
  <%end%>
<br/>

<%= link_to "Supprimer", event_path, :class => "btn btn-lg btn-primary btn-block btn-danger", :data => {:confirm => "Êtes-vous sur?(e)"}, :method => :DELETE %>
</div>

<% if @event.errors.any? %>
  <div class="alert alert-dismissible alert-warning">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong> Bah alors ?! </strong>
  <p>Nous n'avons pas réussi à créer l'Event pour le/les raisons suivantes :</p>
  <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>

</div>
</div>

app/views/events/index.html.erb
<%= render "carousel" %>
<%= render "index" %>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>

    <h1 class="h3 mb-3 font-weight-normal text-center">Créer ton event !</h1>
  <!-- FORMULAIRE DE CRÉATION D'UN EVENT -->
  <%= form_with model: @event, local: true,  html: { class: "form-signin mt-3" } do |f| %>


    <p> Date de début :</br> <%= f.datetime_select :start_date, class: "form-control"%> </p>

    <p> Durée (en minutes) :</br> <%= f.number_field :duration, step: 5, min: 0, class: "form-control"%> </p>


    <p> Description :</br> <%= f.text_field :description, class: "form-control"%> </p>
    <p> Titre :</br> <%= f.text_field :title, class: "form-control"%> </p>


    <p> Prix  :</br> <%= f.number_field :price, min: 0, class: "form-control"%> </p>


    <p> Lieu de l'Event :</br> <%= f.text_field :location, class: "form-control"%></p>
    <div class="actions mt-5">
      <%= f.submit "Submit", class: "btn btn-lg btn-primary btn-block" %>
    </div>
  <%end%>
</div>

<% if @event.errors.any? %>
  <div class="alert alert-dismissible alert-warning">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong> Bah alors ?! </strong>
  <p>Nous n'avons pas réussi à créer l'Event pour le/les raisons suivantes :</p>
  <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>

</div>
</div>

app/views/events/show.html.erb
<%= render "show" %>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>