config/routes.rb
Rails.application.routes.draw do

  root "events#index"
  devise_for :users
  resources :events do 
  	  resources :charges
      resources :attendances
      resources :avatars
  end 
  
  resources :teams
  resources :contacts
  #resources :users do
   # resources :avatars
  #end
  resources :user, :has_one => [:avatar]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController

  def new
  end
  # POST /avatars
  # POST /avatars.json
  def create
    @avatar = Avatar.new(avatar_params)
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])


      if @avatar.save
        flash[:success] =  "Avatar was successfully created." 
        redirect_to '/'
      else
      flash.now[:danger] = "Error attemprint to attend an event"
      render :action => 'new'
      end
  end

 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_avatar
      @avatar = Avatar.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def avatar_params
      params.fetch(:avatar, {})
    end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/views/avatars/edit.html.erb
<h1>Editing Avatar</h1>

<%= render 'form', avatar: @avatar %>

<%= link_to 'Show', @avatar %> |
<%= link_to 'Back', avatars_path %>

app/views/avatars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Avatars</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @avatars.each do |avatar| %>
      <tr>
        <td><%= link_to 'Show', avatar %></td>
        <td><%= link_to 'Edit', edit_avatar_path(avatar) %></td>
        <td><%= link_to 'Destroy', avatar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Avatar', new_avatar_path %>

app/views/avatars/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_avatar_path(@avatar) %> |
<%= link_to 'Back', avatars_path %>