config/routes.rb
Rails.application.routes.draw do

  root "events#index"
  devise_for :users
  resources :events do 
  	  resources :charges
      resources :attendances
      resources :avatars
  end 
  
  resources :teams
  resources :contacts
  #resources :users do
   # resources :avatars
  #end
  resources :user, :has_one => [:avatar]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<!-- FLASH MESSAGES -->
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
 	<!-- Footer -->
<footer class="footer font-small">
  <div class="container-fluid text-center text-md-left">
    <div class="row">
      <div class="col-md-6 mt-md-0 mt-3">
        <h5 class="text-uppercase">Eventbrite</h5>
        <p>Suivez nous sur les réseaux sociaux ! </p>
        <div class="align sm-center align-lg-right">
        	<a class="twitter" href="#" alt="Twitter"><i class="fab fa-twitter fa-2x" alt="Twitter"></i></a> 
        	<a class="facebook ml-5" href="#" alt="Facebook"><i class="fab fa-facebook fa-2x" alt="facebook"></i></a>
        	<a class="instagram ml-5" href="#" alt="Instagram"><i class="fab fa-instagram fa-2x" alt="instagram"></i></a>
        </div>
      </div>
      <hr class="clearfix w-100 d-md-none pb-3">
      <div class="col-md-3 mb-md-0 mb-3">
      </div>
      <div class="col-md-3 mb-md-0 mb-3">
        <h5 class="text-uppercase">Liens</h5>
        <ul class="list-unstyled">
          <li>
            <a href="#!">L'équipe</a>
          </li>
          <li>
            <a href="#!">Contact</a>
          </li>
          <li>
            <a href="#!">Accueil</a>
          </li>
          <li>
            <a href="#!">Mon compte</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright text-center py-3">© 2019 Copyright: Fannyevent | 
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- jQuery  -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  

<nav class="navbar navbar-expand-lg navbar-light bg-light">
<%= link_to "FANNY EVENT WEBSITE" , root_path, :class => "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto">
      <div class="nav-item">
      <li class="nav-link">
      <%= link_to "L'équipe" , teams_path, :class => "nav_item active" %> <span class="sr-only">(current)</span>
      </li>
      </div>
      <div class="nav-item">
      <li class="nav-link">
          <%= link_to "Contact", contacts_path, :class => "nav_item active" %>
        </li>
       </div>
      <form class="form-inline ml-5">
        <%= link_to "Créer ton event !", new_event_path, class: "btn btn-primary"%>
       </form>
      </ul>


      <ul class="navbar-nav justify-content-end">
       <div class="nav-item">
      <li class="nav-link">
      <% if user_signed_in? %>
       <%= link_to "Bienvenue " + current_user.first_name, user_path(current_user.id), :class => "nav_item active" %>
       <% else %>
      <%= link_to "S'inscrire", new_user_registration_path, :class => "nav_item active" %>
      <% end %>  
      </li>
     </div>
     <div class="nav-item">
      <li class="nav-link">
    <% if user_signed_in? %>
      <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete , :class => "nav_item active"%>
     <% else %>
      <%= link_to "Se connecter", new_user_session_path, :class => "nav_item active" %>
    <% end %> 
      </li> 
     </div>
    </ul> 
          
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbriteproject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <meta charset="utf-8">
    <title>Bootswatch: Lux</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="style/style.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<%= render 'layouts/header' %>
<%= render 'layouts/flash'%>
<%= yield %>
<%= render 'layouts/footer'%>

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>